SELECT
'select q.'||TRIM(CAMPOS.RDB$FIELD_NAME)||', q.* from '||TRIM(TABELAS.RDB$RELATION_NAME)||' Q'


FROM RDB$RELATIONS TABELAS,
     RDB$RELATION_FIELDS CAMPOS,
     RDB$FIELDS DADOSCAMPO,
     RDB$TYPES TIPOS

WHERE CAMPOS.RDB$FIELD_NAME LIKE UPPER('%cadas%')
AND TABELAS.RDB$RELATION_NAME = CAMPOS.RDB$RELATION_NAME 
AND CAMPOS.RDB$FIELD_SOURCE = DADOSCAMPO.RDB$FIELD_NAME 
AND DADOSCAMPO.RDB$FIELD_TYPE = TIPOS.RDB$TYPE 
AND TABELAS.RDB$SYSTEM_FLAG = 0
--AND TIPOS.RDB$TYPE_NAME = 'Tipo_de_Campo. Exemplo: BLOB'

GROUP BY TABELAS.RDB$RELATION_NAME, CAMPOS.RDB$FIELD_NAME


